name: Deploy

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: 🚀 Deploy
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          github_token: ${{ secrets.PAT }}
          name: build-artifact
          path: dist

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Set correct path
        run: sed -i "s/\/dist//g" package.json

      - name: Copy files to dist
        run: |
          cp README.md dist
          cp LICENSE dist
          cp package.json dist
          cp .npmignore dist || true

      - name: Create .tgz package using npm pack
        run: |
          cd dist
          npm pack
          mv *.tgz ../release.tgz

      - name: Create GitHub Release with tarball
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          files: release.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
